using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._FTL.ShipWeapons;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client._FTL.ShipWeapons;

[GenerateTypedNameReferences]
public sealed partial class GunnerConsoleWindow : FancyWindow,
    IComputerWindow<ShuttleConsoleBoundInterfaceState>
{

    public GunnerConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        WorldRangeChange(RadarScreen.WorldRange);
        RadarScreen.WorldRangeChanged += WorldRangeChange;
    }

    private void WorldRangeChange(float value)
    {
        RadarRange.Text = $"{value:0}";
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        RadarScreen.SetMatrix(coordinates, angle);
    }

    public void UpdateState(GunnerConsoleBoundInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
        AmmoCounter.Text = scc.CurrentAmmo <= 0 ? "NO AMMO" : $"{scc.CurrentAmmo}/{scc.MaxAmmo}";
        MaxRadarRange.Text = $"{scc.MaxRange:0}";
    }
}
