using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._FTL.FtlPoints;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FTL.FtlPoints;

[GenerateTypedNameReferences]
public sealed partial class StarmapConsole : FancyWindow
{
    private readonly StarmapConsoleBoundUserInterface _owner;
    private IPrototypeManager _protoManager;


    public StarmapConsole(StarmapConsoleBoundUserInterface owner, IPrototypeManager protoManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _owner = owner;

        _protoManager = protoManager;
        Title = Loc.GetString("starmap-computer-title");
    }

    public void UpdateState(StarmapConsoleBoundUserInterfaceState state)
    {
        UpdateStars(state.Stars);
        Stars.Range = state.Range;
    }

    private void UpdateStars(List<Star> stars)
    {
        Stars.SetStars(stars);
    }
}
